name: Build App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

        ### --- GRANT PERMISSION FOR GRADLEW --- ###
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        ### --------- GRADLE BUILD ---------- ###
      - name: Build Application with Gradle
        run: ./gradlew build